version: '3'

services:
  db:
    image: mysql:5.7
    container_name: domcord-db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"

  web:
    image: php:7.2.2-apache
    container_name: domcord-web
    build:
      context: .
      args:
        DOMCORD_LICENSE_KEY: ${DOMCORD_LICENSE_KEY}
    depends_on:
      - db
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
